create Input Types And Form Elements
danielrileyde/challenges pull request #39
Opened 2023-08-22 17:52 UTC by danielrileyde

# Context

This PR aims to tackle [More input types & Forms - A11y](https://github.com/spiced-academy/honey-web-dev/blob/main/sessions/html-forms/challenges-html-forms.md).

# Changes

- [ ] updated A11y labels
- [ ] created email input field and label
- [ ] created date input field and label
- [ ] created 3 radio buttons and subsequent labels
- [ ] created concerns text area and label
- [ ] created 2 check boxes for news letter and data consent with labels
- [ ] created 2 buttons one for reset data and one to submit data

# How to run 

1. Clone repo
2. Checkout this branch
3. Run page in browser

2023-08-22 21:04 UTC, reverbePrintemps commented on html/html-forms/html-forms_Finding-a11y-errors/index.html
Did you mean to lump this file along with the other in this PR?

2023-08-23 17:30 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +            <!-- Date: label & input -->
I recommend not leaving "simple" (ie. for things that are rather explicit/self-explanatory) comments in a shared codebase. But your call : )

2023-08-23 17:30 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +            <label for="relaxed sloths">Relaxed Slothes</label>
```suggestion
            <label for="relaxed-sloths">Relaxed Slothes</label>
```

2023-08-23 17:31 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +            <label for="jumpy kangaroos">Jumpy Kangaroos</label>
```suggestion
            <label for="jump- kangaroos">Jumpy Kangaroos</label>
```

2023-08-23 17:31 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +              id="jumpy kangaroos"
```suggestion
              id="jumpy-kangaroos"
```

2023-08-23 17:31 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +            <label for="thieving racoons">Thieving Racoons</label>
```suggestion
            <label for="thieving-racoons">Thieving Racoons</label>
```

2023-08-23 17:31 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +              id="thieving racoons"
```suggestion
              id="thieving-racoons"
```

2023-08-23 17:34 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +          </label>
Formatting/indentation could be improved here imo, for example: 
```suggestion
          <label for="accept-terms-conditions">
            I accept the terms and conditions
            <input
              type="checkbox"
              name="accept-terms-conditions"
              id="accept-terms-conditions"
            />
          </label>
```

2023-08-23 17:34 UTC, reverbePrintemps commented on html/html-forms/html-forms_zoo/index.html
> +          <button type="'reset">Reset Form</button>
```suggestion
          <button type="reset">Reset Form</button>
```

2023-08-23 17:36 UTC, reverbePrintemps requested changes
Mostly great but I'd request some changes around naming consistency (kebab case), a couple formatting nitpicks and the technically broken "reset" button. 👍

2023-08-23 20:35 UTC, danielrileyde commented on html/html-forms/html-forms_zoo/index.html
> +          <button type="'reset">Reset Form</button>
good spot!

2023-08-23 20:37 UTC, danielrileyde commented
okay, thanks, ill sort out the kebab casing and naming conventions.

2023-09-17 19:33 UTC, merged